### ISSUE TITLE
Displaying overlay when the app is closed

### ISSUE THREAD

**Issue by sudipta1411** [X-SLAYER/flutter_overlay_window#10]
Hi, I want to show the overlay when the main app is closed and a new incmoing call is received. I have created a `BroadcastReceiver` which keeps running when the app is closed. On receiving a new call, it calls a **background callback** when the is closed. In this callback I am calling `FlutterOverlayWindow.showOverlay`. The callback works fine when the app is closed, I have done some print to show this. However when the app is closed, it gives me the following error

    app is in background uid UidRecord{c767979 u0a588 CEM  idle change:cached procs:0 seq(0,0,0)}, null, android.app.BackgroundServiceStartNotAllowedException: Not allowed to start service Intent

Upon investigating the matter further, I found out  [https://stackoverflow.com/a/47654126/1671807](url) and applied the following changes in `FlutterOverlayWindowPlugin.onMethodCall`

    if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            context.startForegroundService(intent);
    } else {
            context.startService(intent);
    }

But now I am getting the following error

    E/AndroidRuntime(20853): java.lang.RuntimeException: Unable to create service flutter.overlay.window.flutter_overlay_window.OverlayService: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.dart.DartExecutor io.flutter.embedding.engine.FlutterEngine.getDartExecutor()' on a null object reference
    E/AndroidRuntime(20853): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4701)
    E/AndroidRuntime(20853): 	at android.app.ActivityThread.access$100(ActivityThread.java:258)
    E/AndroidRuntime(20853): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2230)
    E/AndroidRuntime(20853): 	at android.os.Handler.dispatchMessage(Handler.java:106)
    E/AndroidRuntime(20853): 	at android.os.Looper.loopOnce(Looper.java:233)
    E/AndroidRuntime(20853): 	at android.os.Looper.loop(Looper.java:344)
    E/AndroidRuntime(20853): 	at android.app.ActivityThread.main(ActivityThread.java:8204)
    E/AndroidRuntime(20853): 	at java.lang.reflect.Method.invoke(Native Method)
    E/AndroidRuntime(20853): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
    E/AndroidRuntime(20853): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
    E/AndroidRuntime(20853): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.dart.DartExecutor io.flutter.embedding.engine.FlutterEngine.getDartExecutor()' on a null object reference
    E/AndroidRuntime(20853): 	at flutter.overlay.window.flutter_overlay_window.OverlayService.<init>(OverlayService.java:37)
    E/AndroidRuntime(20853): 	at java.lang.Class.newInstance(Native Method)
    E/AndroidRuntime(20853): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
    E/AndroidRuntime(20853): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:75)
    E/AndroidRuntime(20853): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4670)
    E/AndroidRuntime(20853): 	... 9 more

I am not sure how to solve this. Can you please help?

**Comment by X-SLAYER** [comment]
i don't know how your code exactly will make the app works even when the main is closed but if you try to run the example you will find that It works fine on the background thread else you can use one of the background tasks plugins such like `foreground_task flutter`

**Comment by sudipta1411** [comment]
I have a basic broadcast receiver, which is triggered on any incmoing call. Based on whether my app is in foreground or background(closed), it `invokes` flutter callbacks. This is also done in the `Telephony` plugin for SMS. This park is working. In my background callback I am simply calling `FlutterOverlayWindow.showOverlay`. Here I am getting the above error

   //background callback
    void onNewCallBg(String msg) {
        debugPrint("new incoming call : $msg");
        await FlutterOverlayWindow.showOverlay(
        height: 500,
        enableDrag: true,
        overlayMessage: "TEST",
        alignment: OverlayAlignment.center,
        );
        FlutterOverlayWindow.shareData(jsonEncode(msg));
    }

In your example app, I close the app AFTER I show the opverlay. Here my requirement is different. The app is already closed and I am trying to show the overlay.

**Comment by sudipta1411** [comment]
Here is a sample app using `Telephony` plugin

`main.dart`

    import 'dart:async';
    import 'dart:convert';
    import 'package:flutter/material.dart';
    import 'dart:async';
    import 'package:flutter/services.dart';
    import 'package:flutter_overlay_window/flutter_overlay_window.dart';
    import 'package:flutter_overlay_window_example/overlays/true_caller_overlay.dart';
    import 'package:telephony/telephony.dart';

    void main() {
        runApp(const MyApp());
    }

    @pragma("vm:entry-point")
     void overlayMain() {
        WidgetsFlutterBinding.ensureInitialized();
        runApp(const MaterialApp(
        debugShowCheckedModeBanner: false,
        home: TrueCallerOverlay(),
     ));
    }

    void doPost(String msg) async {
         await FlutterOverlayWindow.showOverlay(
         height: 500,
         enableDrag: true,
         alignment: OverlayAlignment.center,
    );
    FlutterOverlayWindow.shareData(jsonEncode(msg));
    }

     void onNewSmsBg(SmsMessage msg) {
           debugPrint("[CALL_HANDLER] on new sms bg ${msg.body}");
           doPost(msg.body ?? "");
      }

     class MyApp extends StatefulWidget {
          const MyApp({Key? key}) : super(key: key);

          @override
          State<MyApp> createState() => _MyAppState();
      }

      class _MyAppState extends State<MyApp> {
      String _platformVersion = 'Unknown';
      final _smsHandlerPlugin = Telephony.instance;

      @override
      void initState() {
           super.initState();
           initPlatformState();
           initSmsHandler();
      }

    Future<void> initSmsHandler() async {
    var smsPerm = await _smsHandlerPlugin.requestPhoneAndSmsPermissions;
    await FlutterOverlayWindow.requestPermission();
    _smsHandlerPlugin.listenIncomingSms(
      onNewMessage: (msg) {
        debugPrint("on new sms fg ${msg.body}");
      },
     onBackgroundMessage: onNewSmsBg);
    }

    }

I have added `Telephony` as dependency in `pubspec.yaml` and added an entry for the `OverlayService` in my manifest file. Here the same issue. When the app is in foreground `onNewMessage` is called. When the app is minimized, `onNewSmsBg` is called and the overlay window is shown. But when I close my sample app, `onNewSmsBg` is called but I get the above exception and no overlay window is shown. I get the first error mentioned (no service while in background) if I don't modify the code as mentioned above. After the change, I get the second error.

**Comment by X-SLAYER** [comment]
i don't know if I get it but for me when I used the overlay package I used `foreground_task flutter` so even if I closed the app activity the overlay will not be killed cuz I have a running background task 
clone this project and run it to check 
[foreground_app_test](https://github.com/X-SLAYER/foreground_app_test)

**Comment by sudipta1411** [comment]
Thanks for the reply. I will check it. The above link is not working

**Comment by X-SLAYER** [comment]
> The above link is not working

https://github.com/X-SLAYER/foreground_app_test

**Comment by sudipta1411** [comment]
> > The above link is not working
> 
> https://github.com/X-SLAYER/foreground_app_test

Are you refereing to [https://github.com/X-SLAYER/foreground_plugins_test](url) ? Because the above link is not working

**Comment by sudipta1411** [comment]
The problem is that `FlutterEngineCache` does not hold a reference to a flutter engine with id `OverlayConstants.CACHED_TAG` once the app is closed.

**Comment by X-SLAYER** [comment]
i really don't know i will try to check it and get back to you

**Comment by X-SLAYER** [comment]
it's working fine for me just try this project I run the app background task then I closed the main activity after seconds the overlay has been launched from the background check it here 
https://github.com/X-SLAYER/foreground_app_test/blob/main/lib/pages/first_task_handler.dart

**Comment by sudipta1411** [comment]
I have figured out how to run the overlay in background, without using `oreground_task flutter`. As mentioned previously `FlutterEngineCache` does not hold a reference to a flutter engine with id `OverlayConstants.CACHED_TAG` once the app is closed. So in `onCreate` I am checking if cache already has a reference to the engine and if not create a new one. That seems to solve the problem. But now I have started a foreground service (the first error).

The link you have provided is not working. May be some network issue
![Screenshot from 2022-06-15 14-06-13](https://user-images.githubusercontent.com/1386911/173782528-f1c79337-0710-47d4-abe8-5922ae48b83d.png)
.

**Comment by X-SLAYER** [comment]
mb repository was private now it's public

**Comment by sudipta1411** [comment]
Thank you very much

**Comment by sudipta1411** [comment]
Okay, I think the problem still persists. In your code you have started the foreground service and then you have closed tha app. In my case the app is already closed and I am trying to create the service. Again the cache does not hold a reference to the engine. 

Please look into the sample I have provided. In the sample even if I start a foreground task, it's not working.

**Comment by X-SLAYER** [comment]
i don't have any idea about it it's not logic to start an activity while the app is closed even the engine will be killed so I think it's not posible

**Comment by sudipta1411** [comment]
Consider the truecaller app. The app is not actively running all the time. Yet when a call arrives, it shows an overlay with the caller information. This might be a possible use case. Anyway, I am closing it.

**Comment by X-SLAYER** [comment]
> Consider the truecaller app. The app is not actively running all the time. Yet when a call arrives, it shows an overlay with the caller information. This might be a possible use case. Anyway, I am closing it.

the truecaller app has a background service that works it's the same you can use workmanager or flutter_foreground_task plugins

**Comment by razfazz** [comment]
I have the same or a similar issue.

the window overlay **CAN** be started from a background thread ( i use the plugin flutter_background_service) but only when the main activity was called before with the entrypoint 

```
@pragma("vm:entry-point")
void overlayMain() {
```

but when the main activity got deleted by the system and the background service starts the window overlay i get the following error message:

_Fatal Exception: java.lang.RuntimeException: Unable to create service flutter.overlay.window.flutter_overlay_window.OverlayService: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.dart.DartExecutor io.flutter.embedding.engine.FlutterEngine.getDartExecutor()' on a null object reference_

This can be reproduced by adding flutter_background_service to a window overlay project and activate "start on boot". then restart the device and the app crashes

**Comment by Soheldeveloper** [comment]
@sudipta1411  

I face same issue  that you face, my scenario is similar to yours.  

What I want to achieve is. When app is in background  (Kill State) and firebase silent ping receive (in Kill State) I start fore ground service via [https://pub.dev/packages/flutter_background_service](https://pub.dev/packages/flutter_background_service) package

And In foreground service I open the overlay dialog. So same error I face that you faced. 

When I direct put show overlay code on silent firebase ping. It also not worked.

@X-SLAYER  Can you please help us to achieve this. This is very helpful to us.

Thanks
