### ISSUE TITLE
Does it use Google Play services?

### ISSUE THREAD

**Issue by yalihart** [X-SLAYER/flutter_overlay_window#100]
I am trying to use on a device with no Google play services but I am getting an error:

requires the Google Play Store, but it is missing.

`GooglePlayServicesUtil: com.example.geo_gate requires the Google Play Store, but it is missing.`

Does this use Google play services or is something else in my app trying to use them?

**Comment by X-SLAYER** [comment]
The package does not inherently require or depend on Google Play Services for its core functionalities. Therefore, the issue you're experiencing likely stems from another part of your application or from dependencies that indeed require Google Play Services to function correctly.
