### ISSUE TITLE
Android 14 requirese foregroundServiceType 

### ISSUE THREAD

**Issue by ehaborae** [X-SLAYER/flutter_overlay_window#111]
In android 14 the app crashes when you use this package and require to provide foregroundServiceType
 at android manifest file 
 
  E/AndroidRuntime(15889): 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
E/AndroidRuntime(15889): 	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
E/AndroidRuntime(15889): 	at android.os.Parcel.readParcelable(Parcel.java:4852)
E/AndroidRuntime(15889): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
E/AndroidRuntime(15889): 	at android.os.Parcel.createException(Parcel.java:3041)
E/AndroidRuntime(15889): 	at android.os.Parcel.readException(Parcel.java:3024)
E/AndroidRuntime(15889): 	at android.os.Parcel.readException(Parcel.java:2966)
E/AndroidRuntime(15889): 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
E/AndroidRuntime(15889): 	at android.app.Service.startForeground(Service.java:862)
E/AndroidRuntime(15889): 	at androidx.core.app.ServiceCompat$Api34Impl.startForeground(ServiceCompat.java:238)
E/AndroidRuntime(15889): 	at androidx.core.app.ServiceCompat.startForeground(ServiceCompat.java:172)
E/AndroidRuntime(15889): 	at id.flutter.flutter_background_service.BackgroundService.updateNotificationInfo(BackgroundService.java:172)
E/AndroidRuntime(15889): 	at id.flutter.flutter_background_service.BackgroundService.onCreate(BackgroundService.java:105)
E/AndroidRuntime(15889): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4651)
E/AndroidRuntime(15889): 	... 9 more
I/Process (15889): Sending signal. PID: 15889 SIG: 9
Lost connection to device.

**Comment by YoavSl** [comment]
Same problem here.
