### ISSUE TITLE
OverlayFlag.clickThrough not working on Android 12

### ISSUE THREAD

**Issue by razfazz** [X-SLAYER/flutter_overlay_window#12]
this issue is likely related to this.

https://developer.android.com/about/versions/12/behavior-changes-all#untrusted-touch-events

could you please expose the transparency value of the system alert window. 
then we could adapt opacity to make clickthrough overlay work on Android 12 devices

**Comment by X-SLAYER** [comment]
**OverlayFlag.clickThrough** is working on android 12 the fix is pushed [fix clickThrough overlays for Android12](https://github.com/X-SLAYER/flutter_overlay_window/commit/1ba59e0358e5232c236031656268e71cfac62453) but I didn't publish a new release since then but
you can use it like that 

```dart
  flutter_overlay_window:
    git:
      url: git@github.com:X-SLAYER/flutter_overlay_window.git
```

**Comment by razfazz** [comment]
@X-SLAYER thank you very much. i will try that

**Comment by X-SLAYER** [comment]
use it with HTTPS instead of ssh 

```yaml
  flutter_overlay_window:
    git:
      url: https://github.com/X-SLAYER/flutter_overlay_window.git
```

**Comment by razfazz** [comment]
thank you it works now on my Android 12 test devices.
Only on my OnePlus 7 Pro with Android 11 sometimes the screen input gets blocked randomly after wakung up the device.
the window overlay notification is then in state 

"Overlay is activated"
"tap to edit settings or disable"

this is strange because i chose to set another notification title

**Comment by X-SLAYER** [comment]
no that notification it displayed from the android it self some android show an alerts when there is an overlay window

**Comment by razfazz** [comment]
the issue continue to exist on Android 11.  there i have to restart the device because it is not responsive anymore

**Comment by razfazz** [comment]
after more testing i found out that it still blocks touch in some szenarios also on android 12. for example when you open the google play store and press the "install" button on a random app. you will see that the google play app cannot receive touch events

**Comment by zogol** [comment]
having the same issue with google play store. is there a fix for this?

**Comment by X-SLAYER** [comment]
some apps block the click-through like play store for the moment it can't be done only if you made an accessibility service and put the layout manager into it so it's beyond this package for the moment
