### ISSUE TITLE
Support IOS

### ISSUE THREAD

**Issue by ahmeddarafat** [X-SLAYER/flutter_overlay_window#124]

**Comment by manoj1749** [comment]
It can't be done, because in iOS we can get either a full screen overlay or nothing.
This issue can be closed @X-SLAYER

**Comment by Turskyi** [comment]
@X-SLAYER @manoj1749 Hold on, the original request didn't specify that the overlay shouldn't be full-screen. The library name flutter_overlay_window also doesn't necessarily imply that the overlay must be limited to non-full-screen windows. Full-screen overlays could still be a valuable feature for certain use cases on iOS.

Would it make sense to create a new issue requesting support for a full-screen overlay window on iOS? This functionality could align well with the library's goals and expand its usefulness across platforms.
