### ISSUE TITLE
Method channel calls inside the OverlayService class is not working.

### ISSUE THREAD

**Issue by hemandroid** [X-SLAYER/flutter_overlay_window#17]
Hi there,

Method channel calls inside the OverlayService class is not working.

```
E/flutter (14596): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method updateFlag on channel x-slayer/overlay)
E/flutter (14596): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
E/flutter (14596): <asynchronous suspension>
E/flutter (14596): #1      FlutterOverlayWindow.updateFlag (package:flutter_overlay_window/flutter_overlay_window.dart:103:24)
E/flutter (14596): <asynchronous suspension>
E/flutter (14596): 
```

**Comment by zees98** [comment]
Having similar issues, it appears that method channel calls are in the main thread, while the overlay window is being created some where else. Therefore, is unable to access the MainActivity. 

Would love to have a solution soon since a project of mine is blocked by this.

**Comment by X-SLAYER** [comment]
https://github.com/X-SLAYER/flutter_overlay_window/issues/48#issuecomment-1474805011
