### ISSUE TITLE
await FlutterOverlayWindow.resizeOverlay(80, 120); is not working

### ISSUE THREAD

**Issue by hemandroid** [X-SLAYER/flutter_overlay_window#20]
Hi @X-SLAYER resizing the overlay widget is not working as expected. If we resize the UI component with specific height and width it leads to overflow pixel issues, as the UI was changing at the Run Time instead of compile. But if, we use match_parent for both height and width without having any content in the UI. For instance, Container with match_parent for both height and width. It was working fine.

But not for Container having another Row or Column of widgets. It's not working perfectly.

**Comment by X-SLAYER** [comment]
The resize affect the overlay size not the inside Ui so you need to do your logic before you call the resize hide the items or put a singlechildscrollview depends on your inside Ui

**Comment by rahmanrezaee** [comment]
When resize from right show out of screen please check if we resize from left no problem 
(resizing small screen to large)

**Comment by hemandroid** [comment]
Can you provide any example for that resize option? As I have already
shared some screenshots via email.



Regards,
<https://about.me/hemasaicharan?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
Hema sai charan Kothamasu
about.me/hemasaicharan
<https://about.me/hemasaicharan?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=thumb>
