### ISSUE TITLE
click not working

### ISSUE THREAD

**Issue by conank96** [X-SLAYER/flutter_overlay_window#21]
i have folow code like sample but created a bug this.`void main() {
  runApp(const MyApp());
}

@pragma("vm:entry-point")
void overlayMain() {
  runApp(
    const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: OverlayScreen(),
    ),
  );
}
`

and overlays
`  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: Center(
        child: Container(
          height: 100,
          padding: const EdgeInsets.symmetric(vertical: 12.0),
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment.topCenter,
              end: Alignment.bottomRight,
              colors: isGold ? _goldColors : _silverColors,
            ),
            borderRadius: BorderRadius.circular(12.0),
          ),
          child: Container(
            child: Column(
              children: [
                ElevatedButton(
                    onPressed: () async {
                      print("click button share ");
                      await FlutterOverlayWindow.shareData(" data from Overlays");
                    },
                    child: const Text("Share data"))
              ],
            ),
          ),
        ),
      ),
    );
  }
}`

**Comment by X-SLAYER** [comment]
did u set the overlay flag to ``` OverlayFlag.clickThrough ```

**Comment by themon303** [comment]
I set the overlay flag to OverlayFlag.defaultFlag and enableDrag: true. First I can click but when touch overlay and drag it move very little (like I want click on it but I move my hand a little bit) then the overlay can't receive click in Flutter anymore

**Comment by X-SLAYER** [comment]
> I set the overlay flag to OverlayFlag.defaultFlag and enableDrag: true. First I can click but when touch overlay and drag it move very little (like I want click on it but I move my hand a little bit) then the overlay can't receive click in Flutter anymore
> 
> Work around: change line 316 in file OverlayService.java from "return dragging;" to "return false;"

the fix will be available in the next version

**Comment by themon303** [comment]
Thanks @X-SLAYER for the work. I also found another problem and still try to fix but not found the solution yet, related to click event on Overlay. 

The problem is when call "FlutterOverlayWindow.closeOverlay()" from the Overlay (not from the main app like the example). And then call showOverlay again, this time the Overlay cannot receive any touch event in Flutter.
