### ISSUE TITLE
How to send data from overlay to main app

### ISSUE THREAD

**Issue by zees98** [X-SLAYER/flutter_overlay_window#22]
Greetings,

I am trying to send data from overlay to main app. My use case is that whe I tap the overlay, I call: 
 `await FlutterOverlayWindow.shareData("capture");`

Then I the initState of the home widget of the main App, I am listening to the overlay listener
` FlutterOverlayWindow.overlayListener.listen((event) {
      print("Overlay $event");
    });`

Unfortunately, the listener (in the main app) is not triggering when I call shareData (from the overlay).

Please help! 😭
TIA

**Comment by xiaojieonly** [comment]
> Greetings,
> 
> I am trying to send data from overlay to main app. My use case is that whe I tap the overlay, I call: `await FlutterOverlayWindow("capture");`
> 
> Then I the initState of the home widget of the main App, I am listening to the overlay listener ` FlutterOverlayWindow.overlayListener.listen((event) { print("Overlay $event"); });`
> 
> Unfortunately, the listener (in the main app) is not triggering when I call shareData (from the overlay).
> 
> Please help! 😭 TIA

FlutterOverlayWindow.shareData('7hajhsb');  useless too

**Comment by zees98** [comment]
> > Greetings,
> > I am trying to send data from overlay to main app. My use case is that whe I tap the overlay, I call: `await FlutterOverlayWindow("capture");`
> > Then I the initState of the home widget of the main App, I am listening to the overlay listener ` FlutterOverlayWindow.overlayListener.listen((event) { print("Overlay $event"); });`
> > Unfortunately, the listener (in the main app) is not triggering when I call shareData (from the overlay).
> > Please help! 😭 TIA
> 
> FlutterOverlayWindow.shareData('7hajhsb'); useless too

I meant to type FlutterOverlayWindow.shareData('7hajhsb'); 
Sorry for the typo.

**Comment by zees98** [comment]
I was able to communicate between overlay and the app using sockets. My Main App creates a socket server and the overlay connects to that socket server.

My use case was that I wanted to invoke a native method by pressing the overlay. So what happens now is that, when I tap the overlay, it send a string over the socket connection and when my main app receives the message, it decides which native method to invoke. 

I know this is not a fix, but rather a workaround in case the fix is not coming around any time soon. Hope it helps.

**Comment by X-SLAYER** [comment]
hello sorry for that i will try to check and fix that asap you can use the workaround of the socket until the bug get fixed

**Comment by zees98** [comment]
> hello sorry for that i will try to check and fix that asap you can use the workaround of the socket until the bug get fixed

No problem mate take your time 👌🏻
Good luck🤞🏻

**Comment by Karlo-T** [comment]
Hello, has this problem been solved? Or if not can someone explain how to communicate between overlay and the app using sockets. 

What I want to achieve is that when button on overlay is clicked, then text on my main app has to change.

**Comment by rnrllah07** [comment]
> I was able to communicate between overlay and the app using sockets. My Main App creates a socket server and the overlay connects to that socket server.
> 
> My use case was that I wanted to invoke a native method by pressing the overlay. So what happens now is that, when I tap the overlay, it send a string over the socket connection and when my main app receives the message, it decides which native method to invoke.
> 
> I know this is not a fix, but rather a workaround in case the fix is not coming around any time soon. Hope it helps.

I have a question for this. I am trying this package. are we use local socket? and do you have example code for this? and ı need help

**Comment by vinhbui1** [comment]
any update ? I have the same issue here

**Comment by vinhbui1** [comment]
> I have a question for this. I am trying this package. are we use local socket? and do you have example code for this? and ı need help

Example for use socket communicate between overlay and the app   . Pls check this . (https://medium.com/flutter-community/working-with-sockets-in-dart-15b443007bc9)

**Comment by dorlanpabon** [comment]
Amigos pueden usar al comunicación mediante puertos Isolate.



**********************Overlay******************************
En mi caso uso en overlay los siguiente atributos.

  static const String _kPortName = 'overlay_port';
  final _receivePort = ReceivePort();
  static const String _kPortNameHome = 'home_port';
  SendPort? homePort;
  
En initiState del overlay registro el puerto con el nombre;
  
IsolateNameServer.registerPortWithName(_receivePort.sendPort, _kPortName);

_receivePort.listen((message) {
 //Aqui se recibe los mensajes del enviados del home al overlay
  print("message overlay: $message");
});
    
 En el evento onTop() de algun widget del overlay, trato de obtener el puerto del home o main, como ustedes lo usen.
    
homePort ??= IsolateNameServer.lookupPortByName(_kPortNameHome);


##para enviar mensaje del overlay al home usen, luego de haber registrado su homePort con la linea anterior.

homePort.send("texto"), homePort.send(list), homePort.send( { pro:"prop" } ), etc...


******************************MAIN o Home o como lo usen**********************************

Propiedades del main, o home, o como lo usen.

static const String _kPortName = 'overlay_port';
final _receivePort = ReceivePort();
static const String _kPortNameHome = 'home_port';
SendPort? homePort;

metodo initState


IsolateNameServer.registerPortWithName(_receivePort.sendPort, _kPortName);

_receivePort.listen((message) {
 //Aqui se recibe los mensajes del enviados del overlay al home
  print("message overlay: $message");
});

##para enviar mensaje del  home  al overlay usen lo siguiente:

overlayPort.send("texto"), overlayPort.send(list), overlayPort.send( { pro:"prop" } ), etc...

**Comment by X-SLAYER** [comment]
https://github.com/X-SLAYER/flutter_overlay_window/issues/46#issuecomment-1474805153
