### ISSUE TITLE
Clipboard.setData it does not work

### ISSUE THREAD

**Issue by LegendaryMap** [X-SLAYER/flutter_overlay_window#24]
Hello,
I am trying to copy a text that appears in the overlay but it is not copied using
`Clipboard.setData(ClipboardData(text: "your text"));`

My code to start the overlay is as follows
`await FlutterOverlayWindow.showOverlay(
    width: 150,
    height: 691, //765,
    enableDrag: false,
    overlayTitle: t.generals.notify.overlays.title,
    overlayContent: t.generals.notify.overlays.description,
    flag: OverlayFlag.defaultFlag,
    alignment: OverlayAlignment.centerRight,
    visibility: NotificationVisibility.visibilityPublic,
    positionGravity: PositionGravity.auto,
  );`

**Comment by X-SLAYER** [comment]
Doesn't show any errors in the log? so can you share it

**Comment by xiaojieonly** [comment]
> Doesn't show any errors in the log? so can you share it

Almost all invokeMethod in flutter are unavailable，I can help if you need it

**Comment by jack1230** [comment]
> Doesn't show any errors in the log? so can you share it
I use the plugin `clipboard: ^0.1.3`
`await FlutterClipboard.copy('OkOkOk').then( ( value ) async { print("copied"); });`

It doesn't show any error, it even shows the print of copied in the console, but when I hit paste, it doesn't show anything.
Or is there any code to initialize the Clipboard in the widget overlay

**Comment by huuhieupham189** [comment]
You can not set data Clipboard at Overlay. 
-> Send data from Overlay to home then set clipboard data.

<img width="460" alt="Screen Shot 2023-04-12 at 11 05 36" src="https://user-images.githubusercontent.com/24770033/231346711-0e3d1bce-6205-4b93-9db9-0042909984f4.png">
<img width="465" alt="Screen Shot 2023-04-12 at 11 05 47" src="https://user-images.githubusercontent.com/24770033/231346722-5ae4f9b7-72df-46cf-9eb5-9a5bf9b6d978.png">

**Comment by X-SLAYER** [comment]
Settin data directly to the clipboard from an overlay might not be supported in the way you're attempting to implement it. This is because overlays, by their nature, operate in a somewhat isolated context from the main application UI, which can impose certain limitations on direct interactions like clipboard operations.
