### ISSUE TITLE
release version can't show

### ISSUE THREAD

**Issue by linkaituo** [X-SLAYER/flutter_overlay_window#27]
in debug mode, funcion is ok. but when release, can't show the overlay window ,why?

**Comment by X-SLAYER** [comment]
can you post your ```flutter doctor -v```

**Comment by linkaituo** [comment]
![image](https://user-images.githubusercontent.com/5278096/190403203-2b0fcf0f-4730-4ba9-aaf4-5d5d01a0ecb9.png)

**Comment by linkaituo** [comment]
i run the example in the plugin, the same problem, can't show the overlay window.
flutter run --release

**Comment by linkaituo** [comment]
![image](https://user-images.githubusercontent.com/5278096/190403690-9f478da4-5399-4ba1-aa2f-f7423f104b5a.png)

**Comment by linkaituo** [comment]
> Upgrade your flutter version it's related to this [issue 5](https://github.com/X-SLAYER/flutter_overlay_window/issues/5#issuecomment-1124672603)

ok，i  will try
