### ISSUE TITLE
"closeOverlay" method is not implemented with the plugin version 0.3.2.

### ISSUE THREAD

**Issue by kmemo** [X-SLAYER/flutter_overlay_window#28]
With 0.3.2 of the plugin, calling "FlutterOverlayWindow.closeOverlay()" throws MissingPluginException(No implementation found for method close on channel x-slayer/overlay).

When I checked the source code of the fluter_ovelay_window 0.3.2 on my IDE, the copy of "FlutterOverlayWindowPlugin.java" was missing lines 104-111 of the file in this git repository "[FlutterOverlayWindowPlugin.java](https://github.com/X-SLAYER/flutter_overlay_window/blob/main/android/src/main/java/flutter/overlay/window/flutter_overlay_window/FlutterOverlayWindowPlugin.java).

Am I missing something?

**Comment by X-SLAYER** [comment]
if the copy on ur device missing something just try flutter clean or remove the plugin from pubspec and re-install again

**Comment by kmemo** [comment]
Hi, I have done flutter clean couple of times prior to creating this thread. Also, I have deleted locally downloaded cache directory "flutter_overlay_window-0.3.2" however "flutter get" always re-creates the folder with codes with "FlutterOverlayWindowPlugin.java" with missing closeOverlay() support.

Would anyone who is currently using the latest version of this plugin confirm that I am the only one having this problem?

**Comment by X-SLAYER** [comment]
try to run the example folder

**Comment by kmemo** [comment]
Hi, your example calls 
`onPressed: () async {
    await FlutterOverlayWindow.shareData('close');
 },`
to close the overlay, however this is not clearly described in your API reference (I believe) .

But, according to your API reference has "closeOverlay" method and supposes to be implemented as:
`static Future<bool?> closeOverlay() async {
  final bool? _res = await _overlayChannel.invokeMethod('close');
  return _res;
}`

I have been using this "closeOverlay" method to close the opened overlay and your plugin has been throwing an error for each call to the method.
If you say the 1st way is the correct implementation I think you need to add more information to "shareData" method in the reference and remove "closeOverlay" method from the reference.

**Comment by kmemo** [comment]
I have downloaded [tar.gz](https://pub.dev/packages/flutter_overlay_window/versions/0.3.2.tar.gz) file of your plugin ver 0.3.2 form [the versions page of your pulgin on pub.dev](https://pub.dev/packages/flutter_overlay_window/versions).

After un-archiving the file, 
- FlutterOverlayWindowPlugin.java is dated at 2022/07/13
- home_page.dart is dated at 2022/07/16

These are in-consistent with the version information of the plugin.

**Comment by kmemo** [comment]
I have realised this is a duplidate of  [issue #18](https://github.com/X-SLAYER/flutter_overlay_window/issues/18)
