### ISSUE TITLE
No top-level getter 'overlayMain' declared. 

### ISSUE THREAD

**Issue by Djihanegh** [X-SLAYER/flutter_overlay_window#30]
I'am getting this error 

`NoSuchMethodError (NoSuchMethodError: No top-level getter 'overlayMain' declared.
Receiver: top-level
Tried calling: overlayMain)`

Any explantation ?

**Comment by X-SLAYER** [comment]
Did you add the entry point in your main file 
[example/lib/main.dart](https://github.com/X-SLAYER/flutter_overlay_window/blob/main/example/lib/main.dart#L10)
