### ISSUE TITLE
close error

### ISSUE THREAD

**Issue by ssorttang** [X-SLAYER/flutter_overlay_window#32]
Hi

I try to close overlay.
but I got some issue..

please help me!
thanks.

![error](https://user-images.githubusercontent.com/36214108/198433700-0ce0703b-a9e0-49c7-8683-68846319465c.PNG)

[debug]
E/flutter (25852): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel x-slayer/overlay_channel)
E/flutter (25852): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (25852): <asynchronous suspension>
E/flutter (25852): #1      FlutterOverlayWindow.closeOverlay (package:flutter_overlay_window/flutter_overlay_window.dart:83:24)
E/flutter (25852): <asynchronous suspension>
E/flutter (25852):

**Comment by Dennis-Mwea** [comment]
For some reason, the overlay get's destroyed but is still being shown. Could this be related?
![Screenshot 2022-11-04 at 18 14 08](https://user-images.githubusercontent.com/22258295/200010062-21533fec-e3c6-48dd-98d9-f5899d3483e7.png)

**Comment by diego-lipinski-de-castro** [comment]
found any solution?

**Comment by X-SLAYER** [comment]
can you try the latest version using the git before I push new updates to the pub .dev

```yaml
 flutter_overlay_window:
     git:
      url: https://github.com/X-SLAYER/flutter_overlay_window.git
```

**Comment by X-SLAYER** [comment]
https://github.com/X-SLAYER/flutter_overlay_window/issues/48#issuecomment-1474805011
