### ISSUE TITLE
Error with context differences state(Very Need a help)

### ISSUE THREAD

**Issue by buihongvinh** [X-SLAYER/flutter_overlay_window#33]
Error : When you open overlay_windown and terminal the app , and open again (the overlay still run in background but i can not cancel Timer ().
![Screen Shot 2022-10-28 at 08 44 49](https://user-images.githubusercontent.com/72612544/198446307-772f640f-db56-41b4-a179-f0ed72b228e7.png).

![Screen Shot 2022-10-28 at 08 47 13](https://user-images.githubusercontent.com/72612544/198447889-1c32cd0f-7808-4185-bed2-f13286bc0aac.png)

![Screen Shot 2022-10-28 at 08 48 59](https://user-images.githubusercontent.com/72612544/198448972-909c479d-05df-41a1-9533-58c3fb160d20.png)

Steps to Reproduce :
Download  example in Git and add Timer in initState like code below
![Screen Shot 2022-10-28 at 08 54 22](https://user-images.githubusercontent.com/72612544/198450840-1912dcc7-eacf-41d0-8100-7fa72c543b86.png)
in Home Page
![Screen Shot 2022-10-28 at 08 54 54](https://user-images.githubusercontent.com/72612544/198453728-9d0bdaee-2b88-4e58-821c-4cf887a8213e.png)

Run the app , and open overlay windown . => terminate app (kill the app by swipe) 
=>Open app and Click Close Timer .

Thanks you .

**Comment by X-SLAYER** [comment]
https://github.com/X-SLAYER/flutter_overlay_window/issues/46#issuecomment-1474805153
