### ISSUE TITLE
I am trying calling from background alarmmanager its not opening

### ISSUE THREAD

**Issue by toolgaege** [X-SLAYER/flutter_overlay_window#34]
Can you help me for it please ?
system_alert_window is working on background call but it is not good ui

**Comment by mulaRahul** [comment]
Hey @toolgaege, have you considered using [workmanager](https://github.com/fluttercommunity/flutter_workmanager)? As I've tested this package with it.

**Comment by boyd-boyd** [comment]
> Can you help me for it please ? system_alert_window is working on background call but it is not good ui

hey can i ask you , does this plugin give functionality to call it from background acitvity such that show overlay on any app lunch event on device or Firebase notification.

**Comment by toolgaege** [comment]
Yes it is

15 Mar 2023 Çar 12:44 tarihinde boyd-boyd ***@***.***> şunu
yazdı:
