### ISSUE TITLE
how can I go back my app?

### ISSUE THREAD

**Issue by 217wjs** [X-SLAYER/flutter_overlay_window#35]
solved

**Comment by ahmedradwan18** [comment]
how

**Comment by AnyMarvel** [comment]
Can you tell me how to solve it？
I tried many ways and  always encounter the following problems

Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null, null)

**Comment by X-SLAYER** [comment]
you can use this plugin [bg_launcher](https://pub.dev/packages/bg_launcher)

**Comment by DukeJeon** [comment]
@AnyMarvel I'm sorry too late. I was add call.method in FlutterOverlayWindowPlugin.java
just call launch your app
```
context.startActivity(yourApp);
```
