### ISSUE TITLE
Need to set only Messenger Chat Head for Overlay

### ISSUE THREAD

**Issue by NOTtheKRish** [X-SLAYER/flutter_overlay_window#39]
I need to set only Messenger Chat Head... How can I do it??, because when I open the overlay, at first, it covers the entire screen... and then when I tap once, it becomes like a chat head... 

Also, how can I open the APP by clicking on the overlay??

Kindly suggest me best ways to implement my two conditions!!

Thanks in Advance...

**Comment by X-SLAYER** [comment]
You can set the overlay width and height from the beginning like 50 or something like that, and you set the decoration of the container f your overlay to circular 
and for starting the app again, you can try this plugin [bg_launcher](https://pub.dev/packages/bg_launcher)

**Comment by NOTtheKRish** [comment]
Thanks buddy! @X-SLAYER ... I've been searching for this Overlay plugin for like a week... Finally found it!❤️
