### ISSUE TITLE
FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

### ISSUE THREAD

**Issue by sudipta1411** [X-SLAYER/flutter_overlay_window#4]
When I run the `example` app I get the following error
`java.lang.RuntimeException: Unable to create service flutter.overlay.window.flutter_overlay_window.OverlayService: java.lang.IllegalArgumentException: com.example.flutter_overlay_window_example: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(17128): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
`

It seems that in `onCreate` method of `OverlayService`, one needs to pass `PendingIntent.FLAG_IMMUTABLE` while creating the pending intent.

And also how to show some animation when showing the overlay. Right now it just pops up. It would be nice if there is some nice configurable animation.

**Comment by X-SLAYER** [comment]
hello 
i just pushed a fix for this you can test it before I publish a new version 

```yaml
  flutter_overlay_window:
    git:
      url: https://github.com/X-SLAYER/flutter_overlay_window.git
```
for the animation side in the end you will show a flutter view so you can play with that on the flutter side I think

**Comment by sudipta1411** [comment]
@X-SLAYER the proposed solution seems to works. Thanks for such a quick fix.
