### ISSUE TITLE
bubble freezes 

### ISSUE THREAD

**Issue by ahmedradwan18** [X-SLAYER/flutter_overlay_window#41]
sometimes the bubble in the messenger chat head freezes and does not open when I click on it shows me this line at the console

performTraversals mFirst=false windowShouldResize=false viewVisibilityChanged=false mForceNextWindowRelayout=false params={(486,962)(82x82) gr=CENTER sim={adjust=pan} ty=APPLICATION_OVERLAY fmt=TRANSLUCENT

**Comment by dorlanpabon** [comment]
Amigo, parece que el problema de que se congela la burbuja es por este codigo, 
android\src\main\java\flutter\overlay\window\flutter_overlay_window\OverlayService.java
                         
/*
 * lastYPosition = params.y;
 * if (WindowSetup.positionGravity != "none") {
 * windowManager.updateViewLayout(flutterView, params);
 * mTrayTimerTask = new TrayAnimationTimerTask();
 * mTrayAnimationTimer = new Timer();
 * mTrayAnimationTimer.schedule(mTrayTimerTask, 0, 25);
 * }
 * return dragging;
 */
                         
En mi caso lo estoy comentando y funciona de maravillas.
