### ISSUE TITLE
After opening overlay, unable to call any method to execute

### ISSUE THREAD

**Issue by NOTtheKRish** [X-SLAYER/flutter_overlay_window#43]
I've a periodic method to update location... it works fine when the app is opened... but after the overlay is opened by minimizing or closing the app, that method is not working... any suggestion to execute a method periodically, for like 10 seconds once, when the overlay is opened...

Thanks in Advance...

**Comment by X-SLAYER** [comment]
If you want the method to work even when the app is closed, you can call it in the intistate of the Overlay widget or use any background task plugins

**Comment by NOTtheKRish** [comment]
Ok... Let me check
