### ISSUE TITLE
Admob view blank

### ISSUE THREAD

**Issue by blueskypee** [X-SLAYER/flutter_overlay_window#45]
I add google_mobile_ads but banner only show white
D/EgretLoader(29530): EgretLoader(Context context)
D/EgretLoader(29530): The context is not activity
E/flutter (29530): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
E/flutter (29530): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:294:7)
E/flutter (29530): <asynchronous suspension>
E/flutter (29530): #1      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1146:18)
E/flutter (29530): <asynchronous suspension>
E/flutter (29530): #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:792:5)
E/flutter (29530): <asynchronous suspension>

**Comment by X-SLAYER** [comment]
the new version is published you can check the close it works fine [flutter_overlay_window: ^0.4.1](https://pub.dev/packages/flutter_overlay_window)

**Comment by GauravAppdidGithub** [comment]
I'm facing the same issue as @blueskypee 's even after using the latest version.
I'm getting the below-given error if using AdWidget() from google_mobile_ads package.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
                                                                                                    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
                                                                                                    <asynchronous suspension>
                                                                                                    #1      SurfaceAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1017:30)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      AndroidViewController.create (package:flutter/src/services/platform_views.dart:801:5)
                                                                                                    <asynchronous suspension>
