### ISSUE TITLE
Possible to call from an isolate?

### ISSUE THREAD

**Issue by AhsanSarwar45** [X-SLAYER/flutter_overlay_window#46]
I am using [Android Alarm Manager Plus](https://pub.dev/packages/android_alarm_manager_plus) to start an isolate at a fixed time. Now I want to call the overlay from that isolate. So far, I am not seeing any overlay, or any related error messages. My other audio code in the isolate is working though.

Entry point for isolate called by Android Alarm Manager Plus:
```dart
@pragma('vm:entry-point')
void ringAlarm() async {
  var alarms = await FlutterSystemRingtones.getAlarmSounds();
  final DateTime now = DateTime.now();
  final player = AudioPlayer();
  await player.setAudioSource(AudioSource.uri(Uri.parse(alarms[0].uri)));
  player.play();

  await FlutterOverlayWindow.showOverlay();

  FlutterOverlayWindow.overlayListener.listen((event) {
    if (event == "dismiss") {
      FlutterOverlayWindow.closeOverlay();
      player.stop();
    }
  });
}
```

Entry point for overlay:
```dart
@pragma("vm:entry-point")
void overlayMain() {
  runApp(
    MaterialApp(
        home: Scaffold(
          body: TextButton(
            onPressed: () async {
              await FlutterOverlayWindow.shareData("dismiss");
            },
            child: const Text("Dismiss"),
          ),
        )),
  );
}
```

Is it even possible?

`flutter_overlay_window: ^0.3.3`

**Comment by AhsanSarwar45** [comment]
BTW, I learned that the better way to handle the functionality I was looking for was to use full screen notifications. But I would still like to know whether starting overlays from isolates is possible.

**Comment by X-SLAYER** [comment]
i have updates the example run it and check the code on how to communicate between the two isoltaes
