### ISSUE TITLE
when close, the app crash

### ISSUE THREAD

**Issue by linkaituo** [X-SLAYER/flutter_overlay_window#48]
hey:
    when i close the window with: FlutterOverlayWindow.closeOverlay();
    the app will be crash, get log:
   
E/flutter (23445): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.view.ViewParent.requestSendAccessibilityEvent(android.view.View, android.view.accessibility.AccessibilityEvent)' on a null object reference
E/flutter (23445): 	at io.flutter.view.AccessibilityBridge.sendAccessibilityEvent(AccessibilityBridge.java:1908)
E/flutter (23445): 	at io.flutter.view.AccessibilityBridge.sendWindowContentChangeEvent(AccessibilityBridge.java:1967)
E/flutter (23445): 	at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1719)
E/flutter (23445): 	at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:345)
E/flutter (23445): 	at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:762)
E/flutter (23445): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23445): 	at android.os.MessageQueue.next(MessageQueue.java:374)
E/flutter (23445): 	at android.os.Looper.loopOnce(Looper.java:163)
E/flutter (23445): 	at android.os.Looper.loop(Looper.java:293)
E/flutter (23445): 	at android.app.ActivityThread.main(ActivityThread.java:9551)
E/flutter (23445): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23445): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
E/flutter (23445): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)
E/flutter (23445):
F/flutter (23445): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1233)] Check failed: fml::jni::CheckException(env).

    any i will atention?

**Comment by linkaituo** [comment]
i try the example on the project, it's good.
use the example , when close the overlay window, if hot reload, it will crash

**Comment by X-SLAYER** [comment]
the new version is published you can check the close it works fine [flutter_overlay_window: ^0.4.1](https://pub.dev/packages/flutter_overlay_window)

**Comment by linkaituo** [comment]
ok,ths
