### ISSUE TITLE
The overlay window is transparent when released apk

### ISSUE THREAD

**Issue by You-Project** [X-SLAYER/flutter_overlay_window#5]
![KakaoTalk_20220512_013413299](https://user-images.githubusercontent.com/95755380/167902056-123212a8-3b07-4a33-86bf-5ee760e24134.png)

Hello!
First, Thank you for developing the plugin.
I have built the apk example of the plugin, but the overlay window is not visible.
It's like Transparent. Can't touch between the red lines.
Do you know how to solve it?

My device is Galaxy S22 

![KakaoTalk_20220512_013413299](https://user-images.githubusercontent.com/95755380/167903774-6d932187-3bf3-4bda-9a52-5eb58e02c105.png)

**Comment by You-Project** [comment]
Launching lib\main.dart on SM S901N in debug mode...
Running Gradle task 'assembleDebug'...
√  Built build\app\outputs\flutter-apk\app-debug.apk.
E/flutter (24994): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'overlayMain' declared.
E/flutter (24994): Receiver: top-level
E/flutter (24994): Tried calling: overlayMain, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:222)
E/flutter (24994): 
E/flutter (24994): [ERROR:flutter/runtime/dart_isolate.cc(681)] Could not resolve main entrypoint function.
E/flutter (24994): [ERROR:flutter/runtime/dart_isolate.cc(165)] Could not run the run main Dart entrypoint.
E/flutter (24994): [ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
E/flutter (24994): [ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.

**Comment by You-Project** [comment]
Profile mode

E/flutter (29048): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'overlayMain' declared.
E/flutter (29048): Receiver: top-level
E/flutter (29048): Tried calling: overlayMain, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:222)
E/flutter (29048): 
E/flutter (29048): [ERROR:flutter/runtime/dart_isolate.cc(681)] Could not resolve main entrypoint function.
E/flutter (29048): [ERROR:flutter/runtime/dart_isolate.cc(165)] Could not run the run main Dart entrypoint.
E/flutter (29048): [ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
E/flutter (29048): [ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.
Debug service listening on ws://127.0.0.1:10087/iF4ipEORYko=/ws
[log] Started listening
I/BufferQueueProducer(29048): [SurfaceView - com.example.flutter_overlay_window_example/com.example.flutter_overlay_window_example.MainActivity@49305ae@0#1(BLAST Consumer)1](id:717800000001,api:1,p:29048,c:29048) queueBuffer: queued for the first time.
D/ViewRootImpl@6132947[MainActivity](29048): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
D/ViewRootImpl@6132947[MainActivity](29048): Creating frameCompleteCallback
I/SurfaceView@49305ae(29048): uSP: rtp = Rect(0, 0 - 1080, 2340) rtsw = 1080 rtsh = 2340
I/SurfaceView@49305ae(29048): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@49305ae(29048): aOrMT: uB = true t = android.view.SurfaceControl$Transaction@df34728 fN = 1 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:319 
I/SurfaceView@49305ae(29048): aOrMT: vR.mWNT, vR = ViewRootImpl@6132947[MainActivity]
I/ViewRootImpl@6132947[MainActivity](29048): mWNT: t = android.view.SurfaceControl$Transaction@df34728 fN = 1 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 
I/ViewRootImpl@6132947[MainActivity](29048): mWNT: merge t to BBQ
D/ViewRootImpl@6132947[MainActivity](29048): Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
I/BufferQueueProducer(29048): [ViewRootImpl@6132947[MainActivity]#0(BLAST Consumer)0](id:717800000000,api:1,p:29048,c:29048) queueBuffer: queued for the first time.
D/ViewRootImpl@6132947[MainActivity](29048): Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
I/ViewRootImpl@6132947[MainActivity](29048): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4987 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
I/ViewRootImpl@6132947[MainActivity](29048): [DP] rdf()
D/ViewRootImpl@6132947[MainActivity](29048): reportDrawFinished (fn: -1) 
I/ViewRootImpl@6132947[MainActivity](29048): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(29048): startInputInner - Id : 0
I/InputMethodManager(29048): startInputInner - mService.startInputOrWindowGainedFocus
D/InputMethodManager(29048): startInputInner - Id : 0
I/ViewRootImpl@6132947[MainActivity](29048): ViewPostIme pointer 0
I/ViewRootImpl@6132947[MainActivity](29048): ViewPostIme pointer 1
I/ViewRootImpl@6132947[MainActivity](29048): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputTransport(29048): Input channel destroyed: 'ClientS', fd=129
I/ViewRootImpl@6132947[MainActivity](29048): handleAppVisibility mAppVisible=true visible=false
I/SurfaceView@49305ae(29048): onWindowVisibilityChanged(8) false io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340} of ViewRootImpl@6132947[MainActivity]
I/SurfaceView@49305ae(29048): pST: mTmpTransaction.apply, mTmpTransaction = android.view.SurfaceControl$Transaction@bac714b
I/SurfaceView@49305ae(29048): surfaceDestroyed callback.size 1 #2 io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340}
I/SurfaceView@49305ae(29048): updateSurface: mVisible = false mSurface.isValid() = true
I/SurfaceView@49305ae(29048): tryReleaseSurfaces: set mRtReleaseSurfaces = true
I/SurfaceView@49305ae(29048): 130531011 wPL, frameNr = 0
I/SurfaceView@49305ae(29048): remove() from RT android.view.SurfaceView$SurfaceViewPositionUpdateListener@7c7bec3 Surface(name=SurfaceView - com.example.flutter_overlay_window_example/com.example.flutter_overlay_window_example.MainActivity@49305ae@0)/@0x9fdd340
I/SurfaceView@49305ae(29048): remove() io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340} Surface(name=SurfaceView - com.example.flutter_overlay_window_example/com.example.flutter_overlay_window_example.MainActivity@49305ae@0)/@0x9fdd340
I/SurfaceView@49305ae(29048): aOrMT: uB = true t = android.view.SurfaceControl$Transaction@4dd841f fN = 0 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionLost:1785 android.graphics.RenderNode$CompositePositionUpdateListener.positionLost:326 
I/SurfaceView@49305ae(29048): aOrMT: vR.mWNT, vR = ViewRootImpl@6132947[MainActivity]
I/ViewRootImpl@6132947[MainActivity](29048): mWNT: t = android.view.SurfaceControl$Transaction@4dd841f fN = 0 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionLost:1785 
I/ViewRootImpl@6132947[MainActivity](29048): mWNT: merge t to BBQ
D/OpenGLRenderer(29048): setSurface called with nullptr
D/OpenGLRenderer(29048): setSurface() destroyed EGLSurface
D/OpenGLRenderer(29048): destroyEglSurface
I/ViewRootImpl@6132947[MainActivity](29048): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)8 dur=5 res=0x5 s={false 0} ch=true fn=2
I/SurfaceView@49305ae(29048): windowStopped(true) false io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340} of ViewRootImpl@6132947[MainActivity]
D/SurfaceView@49305ae(29048): updateSurface: surface is not valid
D/SurfaceView@49305ae(29048): updateSurface: surface is not valid
I/ViewRootImpl@6132947[MainActivity](29048): stopped(true) old=false
D/SurfaceView@49305ae(29048): updateSurface: surface is not valid
I/ViewRootImpl@6132947[MainActivity](29048): handleAppVisibility mAppVisible=false visible=true
I/SurfaceView@49305ae(29048): onWindowVisibilityChanged(4) false io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340} of ViewRootImpl@6132947[MainActivity]
D/SurfaceView@49305ae(29048): updateSurface: surface is not valid
D/OpenGLRenderer(29048): setSurface called with nullptr
I/ViewRootImpl@6132947[MainActivity](29048): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)4 dur=8 res=0x1 s={false 0} ch=false fn=-1
D/SurfaceView@49305ae(29048): updateSurface: surface is not valid
I/ViewRootImpl@6132947[MainActivity](29048): stopped(false) old=true
[log] status: true
I/ViewRootImpl@6132947[MainActivity](29048): stopped(false) old=false
I/SurfaceView@49305ae(29048): onWindowVisibilityChanged(0) false io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340} of ViewRootImpl@6132947[MainActivity]
D/SurfaceView@49305ae(29048): updateSurface: surface is not valid
D/OpenGLRenderer(29048): setSurface called with nullptr
I/ViewRootImpl@6132947[MainActivity](29048): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=8 res=0x7 s={true -5476376642603722288} ch=true fn=-1
I/SurfaceView@49305ae(29048): windowStopped(false) true io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340} of ViewRootImpl@6132947[MainActivity]
D/OpenGLRenderer(29048): eglCreateWindowSurface
I/SurfaceView@49305ae(29048): pST: sr = Rect(0, 0 - 1080, 2340) sw = 1080 sh = 2340
I/SurfaceView@49305ae(29048): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@49305ae(29048): pST: mTmpTransaction.apply, mTmpTransaction = android.view.SurfaceControl$Transaction@bac714b
I/SurfaceView@49305ae(29048): updateSurface: mVisible = true mSurface.isValid() = true
I/SurfaceView@49305ae(29048): updateSurface: mSurfaceCreated = false surfaceChanged = true visibleChanged = true
I/SurfaceView@49305ae(29048): surfaceCreated 1 #1 io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340}
I/SurfaceView@49305ae(29048): surfaceChanged (1080,2340) 1 #1 io.flutter.embedding.android.FlutterSurfaceView{49305ae V.E...... ........ 0,0-1080,2340}
I/ViewRootImpl@6132947[MainActivity](29048): [DP] dp(1) 1 android.view.SurfaceView.updateSurface:1375 android.view.SurfaceView.setWindowStopped:383 android.view.SurfaceView.surfaceCreated:2051 
I/ViewRootImpl@6132947[MainActivity](29048): [DP] pdf(0) 1 android.view.SurfaceView.notifyDrawFinished:599 android.view.SurfaceView.performDrawFinished:586 android.view.SurfaceView.$r8$lambda$st27mCkd9jfJkTrN_P3qIGKX6NY:0 
I/ViewRootImpl@6132947[MainActivity](29048): [DP] rdf()
D/ViewRootImpl@6132947[MainActivity](29048): reportDrawFinished (fn: -1) 
I/ViewRootImpl@6132947[MainActivity](29048): [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11387 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
D/ViewRootImpl@6132947[MainActivity](29048): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
D/ViewRootImpl@6132947[MainActivity](29048): Creating frameCompleteCallback
I/SurfaceView@49305ae(29048): uSP: rtp = Rect(0, 0 - 1080, 2340) rtsw = 1080 rtsh = 2340
I/SurfaceView@49305ae(29048): onSSPAndSRT: pl = 0 pt = 0 sx = 1.0 sy = 1.0
I/SurfaceView@49305ae(29048): aOrMT: uB = true t = android.view.SurfaceControl$Transaction@f8ce36c fN = 1 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 android.graphics.RenderNode$CompositePositionUpdateListener.positionChanged:319 
I/SurfaceView@49305ae(29048): aOrMT: vR.mWNT, vR = ViewRootImpl@6132947[MainActivity]
I/ViewRootImpl@6132947[MainActivity](29048): mWNT: t = android.view.SurfaceControl$Transaction@f8ce36c fN = 1 android.view.SurfaceView.applyOrMergeTransaction:1628 android.view.SurfaceView.access$500:124 android.view.SurfaceView$SurfaceViewPositionUpdateListener.positionChanged:1728 
I/ViewRootImpl@6132947[MainActivity](29048): mWNT: merge t to BBQ
D/ViewRootImpl@6132947[MainActivity](29048): Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
I/BufferQueueProducer(29048): [ViewRootImpl@6132947[MainActivity]#2(BLAST Consumer)2](id:717800000002,api:1,p:29048,c:29048) queueBuffer: queued for the first time.
D/ViewRootImpl@6132947[MainActivity](29048): Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
I/ViewRootImpl@6132947[MainActivity](29048): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4987 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
I/ViewRootImpl@6132947[MainActivity](29048): [DP] rdf()
D/ViewRootImpl@6132947[MainActivity](29048): reportDrawFinished (fn: -1) 
D/InsetsSourceConsumer(29048): ensureControlAlpha: for ITYPE_NAVIGATION_BAR on com.example.flutter_overlay_window_example/com.example.flutter_overlay_window_example.MainActivity
D/InsetsSourceConsumer(29048): ensureControlAlpha: for ITYPE_STATUS_BAR on com.example.flutter_overlay_window_example/com.example.flutter_overlay_window_example.MainActivity
I/BufferQueueProducer(29048): [SurfaceView - com.example.flutter_overlay_window_example/com.example.flutter_overlay_window_example.MainActivity@49305ae@1#3(BLAST Consumer)3](id:717800000003,api:1,p:29048,c:29048) queueBuffer: queued for the first time.
I/ViewRootImpl@6132947[MainActivity](29048): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(29048): startInputInner - Id : 0
I/InputMethodManager(29048): startInputInner - mService.startInputOrWindowGainedFocus
I/ViewRootImpl@6132947[MainActivity](29048): ViewPostIme pointer 0
I/ViewRootImpl@6132947[MainActivity](29048): ViewPostIme pointer 1
[log] Is Permission Granted: true
I/ViewRootImpl@6132947[MainActivity](29048): ViewPostIme pointer 0
I/ViewRootImpl@6132947[MainActivity](29048): ViewPostIme pointer 1
D/CompatibilityChangeReporter(29048): Compat change id reported: 160794467; UID 10782; state: ENABLED
D/onStartCommand(29048): Service started
I/ViewRootImpl@8420496[](29048): setView = io.flutter.embedding.android.FlutterView@64d8ded TM=true
I/ViewRootImpl@8420496[](29048): Relayout returned: old=(0,81,1080,2340) new=(0,960,1080,1460) req=(1080,500)0 dur=6 res=0x7 s={true -5476376642603513008} ch=true fn=-1
D/OpenGLRenderer(29048): eglCreateWindowSurface
I/ViewRootImpl@8420496[](29048): [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11387 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
D/ViewRootImpl@8420496[](29048): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
D/ViewRootImpl@8420496[](29048): Creating frameCompleteCallback
D/ViewRootImpl@8420496[](29048): Received frameDrawingCallback frameNum=1. Creating transactionCompleteCallback=false
I/BufferQueueProducer(29048): [ViewRootImpl@8420496[]#4(BLAST Consumer)4](id:717800000004,api:1,p:29048,c:29048) queueBuffer: queued for the first time.
D/ViewRootImpl@8420496[](29048): Received frameCompleteCallback  lastAcquiredFrameNum=1 lastAttemptedDrawFrameNum=1
I/ViewRootImpl@8420496[](29048): [DP] pdf(0) 0 android.view.ViewRootImpl.lambda$addFrameCompleteCallbackIfNeeded$3$ViewRootImpl:4987 android.view.ViewRootImpl$$ExternalSyntheticLambda16.run:6 android.os.Handler.handleCallback:938 
I/ViewRootImpl@8420496[](29048): [DP] rdf()
D/ViewRootImpl@8420496[](29048): reportDrawFinished (fn: -1)

**Comment by You-Project** [comment]
Release mode

Launching lib\main.dart on SM S901N in release mode...
Running Gradle task 'assembleRelease'...
√  Built build\app\outputs\flutter-apk\app-release.apk (6.4MB).
Installing build\app\outputs\flutter-apk\app.apk...
E/flutter (29478): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: NoSuchMethodError: No top-level getter 'overlayMain' declared.
E/flutter (29478): Receiver: top-level
E/flutter (29478): Tried calling: overlayMain, stack trace: #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:222)
E/flutter (29478): 
E/flutter (29478): [ERROR:flutter/runtime/dart_isolate.cc(681)] Could not resolve main entrypoint function.
E/flutter (29478): [ERROR:flutter/runtime/dart_isolate.cc(165)] Could not run the run main Dart entrypoint.
E/flutter (29478): [ERROR:flutter/runtime/runtime_controller.cc(381)] Could not create root isolate.
E/flutter (29478): [ERROR:flutter/shell/common/shell.cc(580)] Could not launch engine with configuration.

**Comment by You-Project** [comment]
[√] Flutter (Channel stable, 2.10.5, on Microsoft Windows [Version 10.0.22000.613], locale ko-KR)
    • Flutter version 2.10.5 at D:\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (3 weeks ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at D:\Android\SDK
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.11.31911.196
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code (version 1.67.1)
    • VS Code at C:\Users\yslee\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (4 available)
    • SM S901N (mobile) • R5CT33H0L3J • android-arm64  • Android 12 (API 31)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22000.613]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 101.0.4951.54
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 101.0.1210.39

[√] HTTP Host Availability
    • All required HTTP hosts are available

**Comment by You-Project** [comment]
Wow, I solved it. Thank you!!

**Comment by X-SLAYER** [comment]
with the new update of [Flutter v3.0.0](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0) everything works fine
