### ISSUE TITLE
x position goes to the opposite direction when dragging

### ISSUE THREAD

**Issue by tolotrasamuel** [X-SLAYER/flutter_overlay_window#51]
I am testing the MessengerChatHead example https://pub.dev/packages/flutter_overlay_window/example and when I drag, y position seems to behave correctly, but the x position goes to the opposite direction. When I move left, it goes right and and when I move right, it goes left

**Comment by X-SLAYER** [comment]
i tried your example but the position was inverted instead of the version I have I already tested it on multiple version
can you try to run the latest example I already merged fixes on the main repo
