### ISSUE TITLE
can't change start tip logo

### ISSUE THREAD

**Issue by linkaituo** [X-SLAYER/flutter_overlay_window#54]
hey, the product is good.
just when i use FlutterOverlayWindow.showOverlay to show the overlay window in my pixel 2 phone,
it will pop the tip, and the tip have a logo,not my app logo, it's the flutter default logo,
can i have a method to change the logo or not to pop the tip.
have a good day, ths.

**Comment by X-SLAYER** [comment]
if you mean the notification the overlay takes the app icon by default that set on resources

**Comment by linkaituo** [comment]
ok, i have understand， ths
