### ISSUE TITLE
If the overlay is double, one of those overlay can't close.

### ISSUE THREAD

**Issue by bimantaratirta** [X-SLAYER/flutter_overlay_window#55]
As I told on the title, if the overlay is double, I can't close the one of those. isActive method detect false and closeOverlay not working at that time whenever the overlay is double.

**Comment by sidetraxaudio** [comment]
Go into the java code, find showOverlay() in the FlutterOverlayWindowPlugin.java and add:
if (OverlayService.isRunning) return;

**Comment by Meetmathukiya** [comment]
@sidetraxaudio 
sir i try your solution but its not work for me it still give me multiple overlays after I visit in particular page again in my app

**Comment by bimantaratirta** [comment]
> Go into the java code, find showOverlay() in the FlutterOverlayWindowPlugin.java and add: if (OverlayService.isRunning) return;

This solution doesn't working for me.

**Comment by BolaAshEf** [comment]
I think the problem is creating new flutter engine each time the activity is attached.
So, I tried to edit [onAttachedToActivity] method in [FlutterOverlayWindowPlugin.java] file to be:-
    @Override
    public void onAttachedToActivity(@NonNull ActivityPluginBinding binding) {
        mActivity = binding.getActivity();
        if(FlutterEngineCache.getInstance().get(OverlayConstants.CACHED_TAG) == null){  //<---
            FlutterEngineGroup enn = new FlutterEngineGroup(context);
            DartExecutor.DartEntrypoint dEntry = new DartExecutor.DartEntrypoint(
                    FlutterInjector.instance().flutterLoader().findAppBundlePath(),
                    "overlayMain");
            FlutterEngine engine = enn.createAndRunEngine(context, dEntry);
            FlutterEngineCache.getInstance().put(OverlayConstants.CACHED_TAG, engine);
        }
        binding.addActivityResultListener(this);
    }

**Comment by X-SLAYER** [comment]
Fixed here to avoid duplication of the overlay 

```yaml
  flutter_overlay_window:
    git:
      url: git@github.com:X-SLAYER/flutter_overlay_window.git
      ref: feature/overlay-improvements
```
