### ISSUE TITLE
Sharing data from foreground service 

### ISSUE THREAD

**Issue by boyd-boyd** [X-SLAYER/flutter_overlay_window#56]
The opening and closing of overlay works flawlessly , the data sharing also works when app is open and foreground service is running but when app get closed the data sharing doesn't work and the 
```dart
FlutterOverlayWindow.shareData()
```
returns null, 
it does not causes any error, 

could you point me in direction why this is happening, does it had to do something with the app isolate .

**Comment by X-SLAYER** [comment]
check the example on how i share the data between two isolates

**Comment by boyd-boyd** [comment]
can you tell me one more thing:
i have to register port before i start my foreground service, so I'm initializing my foreground service in my main app, to send data to overlay i had to register the receiver port in overlay class (am i right?) 

i have one more question that is when i kill my app from the app list and then do anything which causes the condition to show overlay  from foreground service the overlay is shown but the code inside the overlay class never runs which means the old overlay is shown so it doesn't matter if  i send the data through port to the overlay.

for  example :
depending upon the data shared to overlay through FlutterOverlayWindow.sharedata() function, different screen is shown and if no data is shared an error screen is shown . so if i run the app and show the overlay after sharing data the overlay is shown with specified screen but now if i kill the app and show overlay the previous overlay is shown instead of error overlay as no data is shared. 

which conclude that if the app is killed and overlay is invoked through the foreground service it displays the old overlay , and the overlay class code is not executed.
```dart
@pragma("vm:entry-point ")
void overlayMain() {
  runApp(ChangeNotifierProvider(
    create: (BuildContext context) {
      return TimerOverlayNotifier();
    },
    child: MaterialApp(
        color: Colors.transparent,
        theme:
            ThemeData.from(colorScheme: lightColorScheme, useMaterial3: true),
        darkTheme: ThemeData.from(
          colorScheme: darkColorScheme,
          useMaterial3: true,
        ),
        themeMode: ThemeMode.system,
        debugShowCheckedModeBanner: false,
        home: const MyOverlayWindow()),//the code inside this never executed if the app is killed
  ));
}
```

is there any workaround to this.

**Comment by rjsdnql123** [comment]
@X-SLAYER where????? : ( 😢

**Comment by rjsdnql123** [comment]
@X-SLAYER where!!!!!!!!!!!!!!!!!!!!!!!!!!???????????????ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ ㅠ.ㅠ

**Comment by X-SLAYER** [comment]
[Example folder](https://github.com/X-SLAYER/flutter_overlay_window/tree/main/example/lib)

**Comment by rjsdnql123** [comment]
Thanks : )

but

@X-SLAYER  If you go to the background, shareData returns `null`

HELP ME ㅠ^ㅠ

**Comment by X-SLAYER** [comment]
yes use the ReceivePort instead of shareData like the example
