### ISSUE TITLE
messanger_chatHead is stuck in the middle along y-axis

### ISSUE THREAD

**Issue by YUSUF-SELEIM** [X-SLAYER/flutter_overlay_window#60]
hello, 
messanger_chatHead is stuck in the middle along y-axis with all positiongravity instances except 'none' it makes it move freely

**Comment by SpongeManiac** [comment]
I'm having this issue too

**Comment by KanNathani** [comment]
I'm having this issue too, overlay is show only centre position.

**Comment by X-SLAYER** [comment]
try the latest package version [flutter_overlay_window: ^0.4.4](https://pub.dev/packages/flutter_overlay_window)
