### ISSUE TITLE
Admob view is empty

### ISSUE THREAD

**Issue by GauravAppdidGithub** [X-SLAYER/flutter_overlay_window#61]
I'm facing the same issue as @blueskypee 's even after using the latest version.
I'm getting the below-given error if using AdWidget() from google_mobile_ads package.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel flutter/platform_views)
#0 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)

https://github.com/X-SLAYER/flutter_overlay_window/issues/1 SurfaceAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1017:30)

https://github.com/X-SLAYER/flutter_overlay_window/issues/2 AndroidViewController.create (package:flutter/src/services/platform_views.dart:801:5)

**Comment by diegohzea** [comment]
any workaround?

**Comment by X-SLAYER** [comment]
related to this https://github.com/X-SLAYER/flutter_overlay_window/issues/87#issuecomment-2028482576
