### ISSUE TITLE
dynamically change the dragging behaviour 

### ISSUE THREAD

**Issue by dhruvpatidar359** [X-SLAYER/flutter_overlay_window#64]
can we have a function to change the dragging behaviour dynamically .
I am trying to use a painter on the overlay using flutter and trying to implement ,character recogonition through it. But the problem is the overlay is moving and there is not option to disable the drag dynamically .

Thanks

**Comment by GauravAppdidGithub** [comment]
I faced the same issue, therefore, I made some changes. 
use the package as given below and pass the boolean value of enableDrag to FlutterOverlayWindow.resizeOverlay()

eg: 
await FlutterOverlayWindow.resizeOverlay(
          WindowSize.matchParent, //width
          WindowSize.matchParent, //height
          false, //enableDrag
        );

flutter_overlay_window:
    git:
      url: https://github.com/GauravAppdidGithub/flutter_overlay_window
      ref: main

**Comment by dhruvpatidar359** [comment]
i will try this

**Comment by sunjiaming** [comment]
I faced the same issue. I need this feature, too.   But is there a way around it？

**Comment by X-SLAYER** [comment]
You can use the resize overlay and pass the enableDrag params
```dart
await FlutterOverlayWindow.resizeOverlay(
                  WindowSize.matchParent,
                  (MediaQuery.of(context).size.height * 5).toInt(),
                  false, // here
                );
```

**Comment by sunjiaming** [comment]
However, the latest version of the plug-in does not support setting this property
