### ISSUE TITLE
How to run flutter_overlay_window from background after main flutter app is closed?

### ISSUE THREAD

**Issue by You-Project** [X-SLAYER/flutter_overlay_window#7]
Hi,

I know that the overlay window needs to be alive main flutter.
But, I want to run it from background after main flutter app is closed..
Is there a way?

**Comment by X-SLAYER** [comment]
did you try to call the showOverlay method when your app is in the background?

**Comment by You-Project** [comment]
No i didn't.
Flutter app -> call the background -> call the showOverlay at background.
It works good before the app is closed.

**Comment by X-SLAYER** [comment]
yes try to use any flutter background plugin and call the method I didn't try it but I think it works fine

**Comment by You-Project** [comment]
Umn
Do you mean running the app in the background??
My app process is 
[ Flutter app -> call the background -> call the showOverlay at background ]
And Close the app. The background is still running.
It's not work that showing an overlay in the background in this state.

**Comment by You-Project** [comment]
I solved it.
Previously, I call the background from the app,
The background calls the app's overlay (entry point).
I couldn't show the overlay after My app was closed.

So, I have fixed to keep running in the background when the app is closed.

It works good.

Thanks a lot!!!

**Comment by abdullah230695** [comment]
> So, I have fixed to keep running in the background when the app is closed.

how did you do that ? pls help
