### ISSUE TITLE
Enhancement Request: Add Option to Navigate to Home Screen from Overlay Screen

### ISSUE THREAD

**Issue by saurabhkumar8112** [X-SLAYER/flutter_overlay_window#72]
Description:
Currently, the Android application lacks an option to navigate directly to the home screen when the overlay screen is displayed. To access the home screen, users are required to close the overlay. In my specific use case, I need to show an overlay on a particular screen and would greatly appreciate the inclusion of an option to navigate to the home screen directly from the overlay page. Implementing this suggestion would provide significant convenience and improve user experience.

Thank you for considering this enhancement.

**Comment by X-SLAYER** [comment]
What do you mean going to home screen ?

**Comment by saurabhkumar8112** [comment]
Marking it close as it's a very specific user requirement for us.
