### ISSUE TITLE
Destroying the overlay window service

### ISSUE THREAD

**Issue by gustavobrian** [X-SLAYER/flutter_overlay_window#75]
thank for your work? solution for work with flutter_background_service?

**Comment by alhajsidd** [comment]
Hello

Issue : calling await FlutterOverlayWindow.closeOverlay(); inside

@pragma('vm:entry-point')
void onStart(ServiceInstance service) 


doesn't close overlay only this log in showing in debug window 

D/OverLay (25067): Destroying the overlay window service


envoirment :
  flutter_overlay_window: ^0.4.3
  flutter_background_service: ^5.0.5



full logs
`
V/FA      (25067): Inactivity, disconnecting from the service
I/TRuntime.CctTransportBackend(25067): Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TRuntime.CctTransportBackend(25067): Status Code: 200
D/onStartCommand(25067): Service started
D/onStartCommand(25067): Service started
W/TextureView(25067): A TextureView or a subclass can only be used with hardware acceleration enabled.
W/FlutterView(25067): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
W/FlutterView(25067): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
W/FlutterView(25067): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
I/flutter (25067): FLUTTER BACKGROUND SERVICE: 2024-03-15 15:01:55.080845
I/flutter (25067): FLUTTER BACKGROUND SERVICE: 2024-03-15 15:01:55.084221
W/Gralloc4(25067): allocator 3.x is not supported
D/HostConnection(25067): HostConnection::get() New Host Connection established 0xb400006ff6678510, tid 25136
D/HostConnection(25067): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_vulkan_async_qsri GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation(25067): eglMakeCurrent: 0xb400006fe66aa640: ver 3 0 (tinfo 0xb400006f867e5350) (first time)
D/EGL_emulation(25067): eglCreateContext: 0xb400006fe6704b60: maj 3 min 0 rcv 3
D/OverLay (25067): Destroying the overlay window service
I/flutter (25067): FLUTTER BACKGROUND SERVICE: 2024-03-15 15:01:57.059586
I/flutter (25067): FLUTTER BACKGROUND SERVICE: 2024-03-15 15:01:57.062040`
