### ISSUE TITLE
 flutter_overlay_window / flutter_background_service

### ISSUE THREAD

**Issue by rxhul4** [X-SLAYER/flutter_overlay_window#77]
how to make this thing work with flutter_background_service 

When i open this overlap with a onpressed button event i can close the overlay manually from the same button as well as  from a another close button created in the overlay itself .

The main issue arrives when i open the overlay from the background service event than i cannot close that overlay widget at all.

**Comment by X-SLAYER** [comment]
Try latest version of the app if the problem still encountered re-open the issue
