### ISSUE TITLE
can't close overlay_window

### ISSUE THREAD

**Issue by Rillwz** [X-SLAYER/flutter_overlay_window#8]
Hi,

overlay_windows run perfectly fine, but I can't close overlay_window.

`E/flutter (15267): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: MissingPluginException(No implementation found for method close on channel x-slayer/overlay)
E/flutter (15267): #0      MethodChannel._invokeMethod
E/flutter (15267): <asynchronous suspension>
E/flutter (15267): #1      FlutterOverlayWindow.closeOverlay
E/flutter (15267): <asynchronous suspension>
E/flutter (15267): #2      _HomePageState.build.<anonymous closure>
E/flutter (15267): <asynchronous suspension>
E/flutter (15267):
`

**Comment by X-SLAYER** [comment]
for the moment if you want to close the overlay you need to close it from the overlay itself until I fix this problem

**Comment by Rillwz** [comment]
![image](https://user-images.githubusercontent.com/73714271/173234116-90d0f99b-175b-4a2f-96f3-a6a7eb624733.png)

**Comment by X-SLAYER** [comment]
overlay close is fixed in the latest push you can try it from master channel before I release the next version
```yaml
  flutter_overlay_window:
    git:
      url: git@github.com:X-SLAYER/flutter_overlay_window.git
```
