### ISSUE TITLE
Android API 33 crashes

### ISSUE THREAD

**Issue by osama450** [X-SLAYER/flutter_overlay_window#81]
Android API 33 crushed : 
java.lang.RuntimeException: Unable to create service flutter.overlay.window.flutter_overlay_window.OverlayService: java.lang.NullPointerException: Attempt to invoke virtual method 'q4.a io.flutter.embedding.engine.a.i()' on a null object reference
E/AndroidRuntime(29721): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5086)
E/AndroidRuntime(29721): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime(29721): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)
E/AndroidRuntime(29721): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29721): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(29721): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(29721): 	at android.app.ActivityThread.main(ActivityThread.java:8757)
E/AndroidRuntime(29721): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29721): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
E/AndroidRuntime(29721): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(29721): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'q4.a io.flutter.embedding.engine.a.i()' on a null object reference
E/AndroidRuntime(29721): 	at flutter.overlay.window.flutter_overlay_window.OverlayService.<init>(Unknown Source:35)
E/AndroidRuntime(29721): 	at java.lang.Class.newInstance(Native Method)
E/AndroidRuntime(29721): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E/AndroidRuntime(29721): 	at androidx.core.app.CoreComponentFactory.instantiateService(Unknown Source:0)
E/AndroidRuntime(29721): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5055)
E/AndroidRuntime(29721): 	... 9 more

**Comment by naveeez10** [comment]
were you able to find any work around to it?

**Comment by Miaoyu0914** [comment]
were you able to find any work around to it? urgent need！！！
