### ISSUE TITLE
Crached when close overlay in android 12

### ISSUE THREAD

**Issue by osama450** [X-SLAYER/flutter_overlay_window#83]
when i try to close overlay many times app crach only in android 12 phons

java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.WindowManager.updateViewLayout(android.view.View, android.view.ViewGroup$LayoutParams)' on a null object reference
E/AndroidRuntime(29160): 	at flutter.overlay.window.flutter_overlay_window.OverlayService$TrayAnimationTimerTask.lambda$run$0$flutter-overlay-window-flutter_overlay_window-OverlayService$TrayAnimationTimerTask(OverlayService.java:355)
E/AndroidRuntime(29160): 	at flutter.overlay.window.flutter_overlay_window.OverlayService$TrayAnimationTimerTask$$ExternalSyntheticLambda0.run(Unknown Source:2)
E/AndroidRuntime(29160): 	at android.os.Handler.handleCallback(Handler.java:900)
E/AndroidRuntime(29160): 	at android.os.Handler.dispatchMessage(Handler.java:103)
E/AndroidRuntime(29160): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(29160): 	at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime(29160): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29160): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(29160): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

**Comment by M-ImranNawaz** [comment]
Assalam-u-Alaikum @osama450!
I hope you are doing well. Have you found any solution regarding crashing?

**Comment by osama450** [comment]
> Assalam-u-Alaikum @osama450! I hope you are doing well. Have you found any solution regarding crashing?

This Fork fix problem : https://github.com/diegohzea/flutter_overlay_window

**Comment by X-SLAYER** [comment]
can you try the new fix here 

```yaml
  flutter_overlay_window:
    git:
      url: git@github.com:X-SLAYER/flutter_overlay_window.git
      ref: feature/overlay-improvements
```
