### ISSUE TITLE
Not able to add any other plugin into the overlay screen

### ISSUE THREAD

**Issue by ugirishm** [X-SLAYER/flutter_overlay_window#87]
Similar to the earlier issue on AdMob, if we add the flutter_chartboost to the overlay screen, we get the same PlatformView issue.

Tried adding other plugins without any UI, those also seems to fail.

**Comment by X-SLAYER** [comment]
Some of the packages don't work on background cuz they are attached to activity you need to make sure the feature doesn't need Activity Context. If that feature needs it, then we must initialize the method channel on `onAttachedToActivity`, which means it is impossible to use in the plugin that works as a background service.
#

**Comment by shamil-kayla** [comment]
> Some of the packages don't work on background cuz they are attached to activity you need to make sure the feature doesn't need Activity Context. If that feature needs it, then we must initialize the method channel on `onAttachedToActivity`, which means it is impossible to use in the plugin that works as a background service.

the same error is happening with Google maps on both hybrid composition and texture layer. is there any possibility?
