### ISSUE TITLE
when call Function showOverlay() nothing action 

### ISSUE THREAD

**Issue by yazanturk** [X-SLAYER/flutter_overlay_window#89]
FlutterOverlayWindow.showOverlay(
           
                width: 200,
           
                height: 200,
                flag: OverlayFlag.defaultFlag,
                enableDrag: true,
                alignment: OverlayAlignment.centerLeft,
              );

**Comment by Naveed-dev30** [comment]
Same

**Comment by saurabhkumar8112** [comment]
did you register the entryPoint `overlayMain`?
