### ISSUE TITLE
Is it possible show overlay_window without flutter app?

### ISSUE THREAD

**Issue by You-Project** [X-SLAYER/flutter_overlay_window#9]
Hi.

I are developing the Auto send SMS/MMS after call with flutter.

I want to develop like this.
1. Open flutter_overlay_window after end of call.
2. Select sms/mms saved.
3. Send.
Only SMS/MMS setting in the Flutter App.

Currently, 
1. Checking end of call by Android reciver.
2. Sharing inform of call by FlutterOverlayWindow.shareData
3. FlutterOverlayWindow.showOverlay

But, It works good before Flutter App closed.
It only works for a few minutes after the Flutter App closed.

Should I develop it by a native Android?

**Comment by X-SLAYER** [comment]
i did't get exactly what you reached but I think you need to show the overlay then shareData

**Comment by You-Project** [comment]
Good.
Increased the display time of the overlay window even after the app is closed.
But, My app is crashed after almost half day.
I think it's not cause of overlay window...
I have to debuging again again..
Thanks a lot!

**Comment by X-SLAYER** [comment]
no problem maybe if you use background tasks try to ignore battery optimizations check the plugin u use it might have it
