### ISSUE TITLE
Unable to create service flutter.overlay.window.flutter_overlay_window.OverlayService: 

### ISSUE THREAD

**Issue by 0xharkirat** [X-SLAYER/flutter_overlay_window#91]
`java.lang.RuntimeException: Unable to create service flutter.overlay.window.flutter_overlay_window.OverlayService: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{fbc3347 10863:com.example.think_lite/u0a198} targetSDK=34`

what does it mean? I am just using example/lib/main.dart

**Comment by 0xharkirat** [comment]
full output:
at android.app.ActivityThread.handleCreateService(ActivityThread.java:4664)
E/AndroidRuntime(10863): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime(10863): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2264)
E/AndroidRuntime(10863): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10863): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(10863): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(10863): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(10863): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10863): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(10863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/AndroidRuntime(10863): Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{fbc3347 10863:com.example.think_lite/u0a198} targetSDK=34
E/AndroidRuntime(10863): 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
E/AndroidRuntime(10863): 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
E/AndroidRuntime(10863): 	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
E/AndroidRuntime(10863): 	at android.os.Parcel.readParcelable(Parcel.java:4852)
E/AndroidRuntime(10863): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
E/AndroidRuntime(10863): 	at android.os.Parcel.createException(Parcel.java:3041)
E/AndroidRuntime(10863): 	at android.os.Parcel.readException(Parcel.java:3024)
E/AndroidRuntime(10863): 	at android.os.Parcel.readException(Parcel.java:2966)
E/AndroidRuntime(10863): 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
E/AndroidRuntime(10863): 	at android.app.Service.startForeground(Service.java:775)
E/AndroidRuntime(10863): 	at flutter.overlay.window.flutter_overlay_window.OverlayService.onCreate(OverlayService.java:253)
E/AndroidRuntime(10863): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4651)
E/AndroidRuntime(10863): 	... 9 more

**Comment by sarthakydv** [comment]
You need to specify the service type
https://developer.android.com/about/versions/14/changes/fgs-types-required

Also, change the target sdk to 34 in your fork

**Comment by dcdj99** [comment]
> You need to specify the service type https://developer.android.com/about/versions/14/changes/fgs-types-required
> 
> Also, change the target sdk to 34 in your fork

What is the service type that you used for overlay? I already have a foreground service running but unable to get the correct type for this.

**Comment by sarthakydv** [comment]
`specialUse`
