### ISSUE TITLE
Unable to create multiple overlay window.

### ISSUE THREAD

**Issue by jijormathew** [X-SLAYER/flutter_overlay_window#97]
Hello, how can I make numerous overlay windows with this package? I should also be able to close each window separately.

**Comment by saurabhkumar8112** [comment]
Please try to add minimal example of the code that you're using. As it says in the docs and sample example creating a new overlay should be as simple as simply calling showOverlay

**Comment by jijormathew** [comment]
import 'dart:async';
import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:flutter_overlay_window/flutter_overlay_window.dart';

import 'news_data.dart';

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key});
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
            title: const Text('Top Stories'),
            centerTitle: false,
            titleTextStyle: const TextStyle(
                fontSize: 30,
                color: Colors.black)),
        body: ListView.separated(
          shrinkWrap: true,
          separatorBuilder: (context, idx) {
            return const Divider();
          },
          itemCount: getNewsStories().length,
          itemBuilder: (context, idx) {
            final article = getNewsStories()[idx];
            return ListTile(
              onLongPress: (){
                _closeOverlayWindow();
              },
              key: Key('$idx ${article.hashCode}'),
              title: Text(article.title),
              subtitle: Text(article.description),
              onTap: () {
                _showOverlayWindow();
              },
            );
          },
         ));
       
  }
_showOverlayWindow() async {
  bool status = await FlutterOverlayWindow.isPermissionGranted();
  if(!status){
    status = await FlutterOverlayWindow.requestPermission() ?? false;
    setState(() {
    });
  }else{
     await FlutterOverlayWindow.showOverlay(alignment: OverlayAlignment.centerLeft,height: 200,width: 300,enableDrag:  true,flag: OverlayFlag.defaultFlag,positionGravity: PositionGravity.auto);
  }
}
_closeOverlayWindow() async {
  await FlutterOverlayWindow.closeOverlay();
}
} This is the example code that I'm attempting to run. I want to launch an overlay window as I press each article, not replace the one that's already open.

**Comment by ducviet321** [comment]
@jijormathew  Could you put it in a code block? 

By the way, is there any example of using & communicating between multiple of windows?

**Comment by X-SLAYER** [comment]
For the moment this package works only on displaying single overlay
